version: "3.3"
services:
  api:
    image: ${IMAGE_NAME}
    build: .
    ports:
      - "8501:8501"
    networks:
      - web_net
    volumes:
      - /logs
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2"
      replicas: 1
    working_dir: /app
networks:
  web_net:
    driver: overlay
    attachable: true
